def print_event(event):
    print("___________")
    print(f"Handled       : {event.handled}\n"
        f"Timestamp     : {event.timestamp}\n"
        f"Status        : {event.status}\n"
        f"Data1         : {event.data1}\n"
        f"Data2         : {event.data2}\n"
        f"Port          : {event.port}\n"
        f"Note          : {event.note}\n"
        f"Velocity      : {event.velocity}\n"
        f"Pressure      : {event.pressure}\n"
        f"ProgNum       : {event.progNum}\n"
        f"ControlNum    : {event.controlNum}\n"
        f"ControlVal    : {event.controlVal}\n"
        f"PitchBend     : {event.pitchBend}\n"
        f"Sysex         : {event.sysex}\n"
        f"IsIncrement   : {event.isIncrement}\n"
        f"Res           : {event.res}\n"
        f"InEv          : {event.inEv}\n"
        f"OutEv         : {event.outEv}\n"
        f"MidiId        : {event.midiId}\n"
        f"MidiChan      : {event.midiChan}\n"
        f"MidiChanEx    : {event.midiChanEx}"
    )